version: "3"
services:
  db:
    image: "postgres"
    container_name: "rabang_postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/rabang
    environment:
      - POSTGRES_USER=itechs
      - POSTGRES_PASSWORD=itechs!228
      - POSTGRES_DB=rabang

  redis:
    image: "redis"
    container_name: "rabang-redis"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data/redis/rabang
    restart: always
volumes:
  rabang_data:
